language: node_js
node_js:
    - "node"
    - "6"
install:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
    - npm install
script:
    - npm run test
    - npm run benchmark
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
